### ISSUE TITLE
{ ordinals: true } option

### ISSUE THREAD

**Issue by rxaviers** [eemeli/make-plural.js#8]
Hi @eemeli,

Documentation says

> The optional `opt` parameter may contain the following boolean members:
* `cardinals` — if true, rules for cardinal values (1 day, 2 days, etc.) are 
  included
* `ordinals` — if true, rules for ordinal values (1st, 2nd, etc.) are included

> If both `opt.ordinals` and `opt.cardinals` are true, the returned function takes
a second parameter `ord`. Then, if `ord` is true, the function will return the
ordinal rather than cardinal category applicable to `n` in locale `lc`.

By passing `{ordinals: true, cardinals: false}`, I expect that the "function will return the
ordinal rather than cardinal". But, currently the returned function also depends on the state of `MakePlural.cardinals` (https://github.com/eemeli/make-plural.js/blob/4a663fe3cae92c18e6e574ec5b63f9c70ba35f85/src/make-plural.js#L126-L127) (whether or not it has been set previously).

I am wondering if we could change the API to make it more consistent. Some ideas:
 1. Consider options only, independently of MakePlural.cardinals or MakePlural.ordinals being set. [1]
 1. Change options to allow something in this line `{provide: "cardinal"}`, `{provide: "ordinal"}`, or `{provide: "both"}`.

1: 
```diff
--- a/src/make-plural.js
+++ b/src/make-plural.js
@@ -123,8 +123,11 @@ export default class MakePlural {
             lc = opt.lc;
         }
         this.lc = lc || MakePlural.lc;
-        this.cardinals = opt.cardinals || MakePlural.cardinals;
-        this.ordinals = opt.ordinals || MakePlural.ordinals;
+        this.cardinals = opt.cardinals;
+        this.ordinals = opt.ordinals;
+        if (!this.ordinals && !this.cardinals) {
+            this.cardinals = MakePlural.cardinals;
+        }
         if (!this.ordinals && !this.cardinals) throw new Error('At least one ty
         this.categories = { cardinal: [], ordinal: [] };
         this.parser = new Parser();
```

**Comment by tniessen** [comment]
Actually, cce9549 introduced inconsistency with the documentation:

> If lc or the opt values are not set, the values are taken from MakePlural.lc (no default value), MakePlural.cardinals (default true) and MakePlural.ordinals (default false).

This was true before cce9549 and - in my opinion - a comprehensible behavior. Previous versions checked for the existence of the `opt` argument and used `MakePlural.cardinals` / `MakePlural.ordinals` accordingly (see https://github.com/eemeli/make-plural.js/blob/989e55574cb213c3306c979a4dccd9f583f1d6a8/src/make-plural.js#L163-L164). However, using ES6 default parameters to automatically assign an empty object to `opt` eliminates the possibility to check whether the parameter was passed.

Another suggestion (I tend to use `x == null` instead of `typeof x == 'undefined'`):
```diff
+        if (opt.cardinals == null && opt.ordinals == null) {
+            this.cardinals = MakePlural.cardinals;
+            this.ordinals = MakePlural.ordinals;
+        } else {
+            this.cardinals = opt.cardinals;
+            this.ordinals = opt.ordinals;
+        }
-        this.cardinals = opt.cardinals || MakePlural.cardinals;
-        this.ordinals = opt.ordinals || MakePlural.ordinals;
```
This one is slightly longer, but should cover all edge cases.

**Comment by eemeli** [comment]
You're right, `opt = { cardinals: false }` doesn't work as it should. I think the smallest change to get it to work like I intended would be this:

```diff
@@ -123,8 +123,8 @@ export default class MakePlural {
             lc = opt.lc;
         }
         this.lc = lc || MakePlural.lc;
-        this.cardinals = opt.cardinals || MakePlural.cardinals;
-        this.ordinals = opt.ordinals || MakePlural.ordinals;
+        this.cardinals = ('cardinals' in opt) ? opt.cardinals : MakePlural.cardinals;
+        this.ordinals = ('ordinals' in opt) ? opt.ordinals : MakePlural.ordinals;
         if (!this.ordinals && !this.cardinals) throw new Error('At least one type of plural is required');
         this.categories = { cardinal: [], ordinal: [] };
         this.parser = new Parser();
```

However, I'm tempted to go for the following as it seems more ES6-ish:

```diff
@@ -117,19 +117,14 @@ class Tests {
 }
 
 export default class MakePlural {
-    constructor(lc, opt = {}) {
-        if (typeof lc == 'object') {
-            opt = lc;
-            lc = opt.lc;
-        }
+    constructor(lc, { cardinals = MakePlural.cardinals,
+                      ordinals = MakePlural.ordinals } = {}) {
         this.lc = lc || MakePlural.lc;
-        this.cardinals = opt.cardinals || MakePlural.cardinals;
-        this.ordinals = opt.ordinals || MakePlural.ordinals;
-        if (!this.ordinals && !this.cardinals) throw new Error('At least one type of plural is required');
+        if (!ordinals && !cardinals) throw new Error('At least one type of plural is required');
         this.categories = { cardinal: [], ordinal: [] };
         this.parser = new Parser();
         this.tests = new Tests(this);
-        this.fn = this.buildFunction();
+        this.fn = this.buildFunction(cardinals, ordinals);
         this.fn._obj = this;
         this.fn.categories = this.categories;
         this.fn.test = function() { return this.tests.testAll() && this.fn; }.bind(this);
```

That would mean dropping the (undocumented) single-object form of parameter entry, which I'm not actually sure is useful.

Opinions?

**Comment by tniessen** [comment]
@eemeli That depends on how you want it to work. The problem with your suggestion is that it is still not safe to pass `{ ordinals: true }`.

According to the documentation, setting `ordinals` to `true` should enable rules for ordinal values. In fact, as `('cardinals' in opt) === false` and `MakePlural.cardinals === true`, it will actually contain both types of rules. In my opinion, it is not very intuitive to specify `{ ordinals: true, cardinals: false }`. It should not be necessary to explicitly disable something you never enabled.

Additionally, there is no guarantee that `{ ordinals: true }` will always use both types of rules unless you can guarantee that `MakePlural.cardinals === true`. If that is true, the property `MakePlural.cardinals` can be considered unnecessary.

I think the only situation where `MakePlural.ordinals` and `MakePlural.cardinals` can be used reasonably is if neither `opt.ordinals` nor `opt.cardinals` is set (see my suggestion above). This would match the old behavior which was quite handy and did not create any conflicts.

Another possibility would be to follow @rxaviers' second idea, but that would involve an API change. Alternatively, you might consider removing `MakePlural.ordinals` and `MakePlural.cardinals`. I can think of way more problems than benefits due to those properties.

**Comment by rxaviers** [comment]
@eemeli, I feel the way @tniessen has described.

What do you think of @tniessen's proposal "MakePlural.ordinals and MakePlural.cardinals can be used reasonably is if neither opt.ordinals nor opt.cardinals is set"?

**Comment by eemeli** [comment]
You're right (again). I made it work as you suggested; the static values are read from `MakePlural` only if the second param is unset.

**Comment by rxaviers** [comment]
Thank you @eemeli. I really liked the code you came up with, very concise.

**Comment by tniessen** [comment]
Agree with @rxaviers, very clever solution! Thanks @eemeli!
